### ISSUE TITLE
Offline First Support

### ISSUE THREAD

**Issue by zoomclub** [jsayol/rxfirebase#1]
Just wondering, how will offline editing work after a app restart, when there is no internet connection available? From what I can tell Firebase does support this offline first mode of operation on iOS and Android but not the Web platform, what a shame.

Also PWAs with Service Workers are introducing offline caching/storage, it would be good to leverage this if possible? I've been hoping this would get solved in a elegant way (or any way for that matter) for sometime. What do you think, is there any hope to fill this gaping hole in Firebase?

**Comment by zoomclub** [comment]
I certainly did not mean to just dump my offline concern on your doorstep, just thought that rxfirebase might be the right place to solve this too, since it intends to handle all the other Firebase services.

There is a wrapper that seems closest to being the right type of solution here: https://github.com/yeldarby/offline-firebase, it just needs to be updated to Firebase v3, not sure why it never was? Maybe this idea is what Polymer is doing here? https://elements.polymer-project.org/elements/app-storage?active=app-indexeddb-mirror.

It would be good to have a solution that is as tight with Firebase as possible. Meanwhile, the general desire for a solution remains strong, see: https://groups.google.com/forum/#!topic/firebase-talk/5KrPMg-LhQk

Cheers

**Comment by jsayol** [comment]
Hey @zoomclub, thanks for opening this issue. What you're proposing is quite interesting but it certainly falls out of the scope of this tiny library. I'd much rather wait and see how the Firebase team decides to tackle this themselves.

I'll keep an eye on any new releases of the web SDK to make sure any changes in that regard are also supported here too.

Thanks!
